#ifndef BIS_TOKENTYPE_HPP
#define BIS_TOKENTYPE_HPP

enum class TokenType
{
    // Single-character tokens
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SLASH, SEMICOLON, STAR,

    // One or two character tokens
    RIGHT_BRACKET, LEFT_BRACKET, EXCLAMATION, EXCLAMATION_EQUAL, EQUAL,
    EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, MINUS_MINUS, PLUS_PLUS,

    // Literal
    IDENTIFIER, STRING, NUMBER,

    // Keyword
    AND, OR, CLASS, IF, ELSE, ELIF, _FALSE, _TRUE, FN, FOR, 
    WHILE, NIL, PRINT, RETURN, SUPER, THIS, VAR, LAMBDA, BREAK, CONTINUE,

    _EOF
};

#endif // BIS_TOKENTYPE_HPP